name: CI Pipeline

on:
  push:
    branches: [ main ]  # Runs on push to the 'main' branch
  pull_request:
    branches: [ main ]  # Runs on pull requests to the 'main' branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Specifies that the job runs on the latest version of Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # This action checks out your repository

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Set your Python version here

    - name: Install dependencies
      run: |
        python -m venv venv  # Create virtual environment
        source venv/bin/activate  # Activate the virtual environment
        pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt  # Install dependencies

    - name: Set PYTHONPATH  # Ensure the app module can be found
      run: |
        echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

    - name: Run flake8  # Linting with flake8 for code quality
      run: |
        source venv/bin/activate
        pip install flake8  # Install flake8 if not already in requirements.txt
        flake8 app/ tests/  # Run flake8 on your app and tests directories

    - name: Run tests with coverage  # Run tests and measure coverage
      run: |
        source venv/bin/activate  # Activate virtual environment
        pip install coverage  # Install coverage if not already in requirements.txt
        coverage run -m pytest  # Run tests with coverage
        coverage report  # Print the coverage report
